#!/bin/zsh
fpid=$(pidof plugin-container)

fd=$(lsof | grep $fpid | /bin/grep '(deleted)' | /bin/grep -o '[0-9]*u ' | head -1)

fd=$fd[1,-3]

print /proc/$fpid/fd/$fd

[[ -n $1 ]] && exit

mplayer /proc/$fpid/fd/$fd
