#!/bin/zsh
# detect git first

trap 'print -n;exit 1' INT
autoload -U colors && colors
isgit="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
if [[ -n $isgit && $isgit == "true" ]];then
     local gprompt="("
     gprompt+="$(git branch | cut -d ' ' -f 2)"
     if [[ -n $(git status -s) ]];then gprompt+="⚡"; fi
     gprompt+=")"
     printf " %s%s" "%{${fg[yellow]}%}" $gprompt
fi

