#!/bin/zsh
# detect git first

trap 'print -n;exit 1' INT
autoload -U colors && colors
#isgit="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
#isgit="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
if  test (../)#.git(N) 2>/dev/null;then
     local gprompt="("
     gprompt+="$(git branch | grep '*'| cut -d ' ' -f 2  | tr -d '\n')"
     #timeout 3 git status -s 
     if [[ -n $(timeout -s KILL 2 git status -s) ]];then 
         gprompt+="⚡"; 
     else
         gprompt+="ʃ";
     fi
     gprompt+=")"
     printf " %s%s" "%{${fg[yellow]}%}" $gprompt
fi

