#!/bin/zsh
daemons=($@)
#print -l $daemons

while :
do
    for d in $daemons
    do
            if [[ -f /var/run/daemons/$d ]] && ! ps auxww | /bin/grep -i $d | grep -v mnger |  grep -v grep &>/dev/null
            then
                    echo "Restarting service $d..."
                    sudo /etc/rc.d/$d stop
                    sleep 5
                    sudo /etc/rc.d/$d start
            fi
    done
    sleep 60
    # Heartbeat for flash
    cpu=$(top -b -n 1 | grep plugin-cont | head -1 | awk '{ print $9 }')
    if [[ -n $cpu && $cpu -gt 2 ]];then
         xdotool key ctrl
    fi
    sleep 60
done
