#!/bin/zsh
#set -x
#latest=$(/bin/ls -A /tmp/mplayer/ | tail -1)
#rm -f /tmp/mplayer.fif
#ln -sf /tmp/mplayer/$latest /tmp/mplayer.fif
# Responsibility transferred to server

switch(){
latest=$(/bin/ls -A /tmp/mplayer/ | tail -2 | head -1)
#rm -f /tmp/mplayer.fif
ln -sf /tmp/mplayer/$latest /tmp/mplayer.fif
}

active(){
    for ff in  /tmp/mplayer/*.fif;do
        echo "get_property filename" > $ff
        if ! tail -1 /tmp/mplayer.log | /bin/grep  PROPERTY_UNAVAILABLE;then
            ln -sf $ff /tmp/mplayer.fif
            break
        fi
    done
}

export yprofile="mplayeraux"

border(){
    #return
    #set -x
    xprop -name MPlayer
    fs=$(xprop -name MPlayer | /bin/grep -i "1280/800" | wc -l)
    #fs=$(isfullscreen)
    echo "vo_fullscreen" > $MPSOCKET
    if [[ $fs -gt 0 ]];then
        #xmonad fu
        sleep 1
       xdotool key super+r
    fi
    #set +x
}

isfullscreen(){
    echo "get_vo_fullscreen" > $MPSOCKET
    sleep 1
    #sync
    isit=$(/bin/grep --line-buffered ANS_VO_FULLSCREEN /tmp/mplayer.log | tail -1 | cut -d = -f 2) 
    echo $isit
}

echo_and_test(){
    echo "get_property filename" > $MPSOCKET
    if ! tail -1 /tmp/mplayer.log | /bin/grep PROPERTY_UNAVAILABLE;then
        return 0
    fi
    return 1
}

#active
echo_and_test || active 

if [[ $1 == "stop" ]];then
    #if pgrep mplayer &>/dev/null;then
        echo 'get_time_pos' >$MPSOCKET
        echo 'get_property path' > $MPSOCKET 
        echo 'stop' >$MPSOCKET
    #fi
    sleep 3
    LOG="tail -5 /tmp/mplayer.log"
    position=`${=LOG} | /bin/grep ANS_TIME_POSITION | head -1 |  cut -d "=" -f 2`
    file=`${=LOG} | /bin/grep ANS_path | head -1 |  cut -d "=" -f 2`
    echo "#STOPPED ${=file}" >> /tmp/mplayer.log
    echo "${=file}:${=position}" >>~/.mplayer.hist
    #switch

elif [[ $1 == "border" ]];then
    border

elif [[ $1 == "pause" ]];then
    mpc pause &>/dev/null
    echo 'pause' > $MPSOCKET

elif [[ $1 == "bookmark" ]];then
    echo 'get_time_pos' > $MPSOCKET
    echo 'get_property path' > $MPSOCKET
    sleep 4
    LOG="tail -5 /tmp/mplayer.log"
    position=`${=LOG} | /bin/grep ANS_TIME_POSITION | head -1 |  cut -d "=" -f 2`
    file=`${=LOG} | /bin/grep ANS_path | head -1 |  cut -d "=" -f 2`
    add_text="$(zenity --text 'Tags if any' --entry)"
    echo "$file:$position:${add_text// /,}" >> ~/.mplayer.bookmarks

elif [[ $1 == "extract" ]];then
    file=$(cat ~/.mplayer.bookmarks | ${(e)=YDMENU} | tr ':' '#' )
    while [[ ! -z $file ]];do
        echo "loadfile \"${file[(ws:#:)1]}\"" > $MPSOCKET
        echo "set_property time_pos ${file[(ws:#:)2]}" > $MPSOCKET
        sleep 3
        while ! tail -2 /tmp/mplayer.log | /bin/grep "#STOPPED ${file[(ws:#:)1]}";do sleep 3;done
        file=$(cat ~/.mplayer.bookmarks | ${(e)=YDMENU} | tr ':' '#')
    done

elif [[ $1 == "cleanup" ]];then
    # Assumption: mplayer is already stopped
    #timeout -k 10 4 ~/bin/mplayeraux stop
    rm /tmp/mplayer/*
    killall -9 mplayer
    rm /tmp/locks/mplayer*
fi

#set +x

