#!/bin/zsh
#set -x
xnotify(){
    heading="$1"
    shift
    rest="$@"
    /usr/bin/notify-send -t 10000 "$heading" "$rest"  #2>|/tmp/notifylog
}

cnotify(){
muxSend a "echo $@"
}

type=xnotify

export DISPLAY=":0"
pidof X &>/dev/null || type=cnotify


param="$1"
mlog="$@"

if [[ $0 == *aria* ]];then
    param="aria2c"
    mlog="Aria2c: $(tail -1 ~/.download_history)"
fi

echo -e "\n$(date '+%F %H:%M') ==> $mlog\n" >> ~/.notify-history

case $param in
    *rtorrent*)
      $type "Torrent download" "$1 download complete!"
      consume $HOME/.dque
      ;;
      *aria2c*)
        message=$(tail -1 ~/.download_history |cut -d ' ' -f 1 | cut -d : -f 2-)
        $type "Aria2:" "${message:t}
        <i>download complete</i>"
        consume $HOME/.dque
        ;;
     *) $type "$param" "$@"
esac
#set +x
