#!/bin/zsh
maxthres=5
thres=$maxthres
duration=5

xnotify(){
    heading="${(Q)1}"
    shift
    rest="$@"
    rest=${(Q)rest}
    text=$(echo "^fg(green)$heading[1,15]: ^fg(grey85)$rest" | perl -pe 'if (!eof()) { s/\n/ | /g }' | tr -dc '[:print:]' )
    echo "$text" | dzen2  -p $duration -xs 2 -y -1 &!
}
cnotify(){
    tmux display-message '$@'
    #muxSend a "echo $@ | head -1  | tr  '\n' ' | ' | tr -dc '[:print:]' "
}

type=xnotify

export DISPLAY=":0"
pidof X &>/dev/null || type=cnotify

NFILE="/dev/shm/.notify-counter"

if [[ $1 == "-f" ]];then
    shift
    duration=2
    $type "$@"
    exit
fi

if [[ ! -f $NFILE ]];then
    temp=$(date +%s)
    echo "$temp|shot|$maxthres" >| $NFILE
    echo  " " >> $NFILE
    njiffy=$temp
    mode=shot
    time=$temp
    difference=100
else
    t=$(< $NFILE)
    temp=$t[(f)1]
    p_subject=$t[(f)2]
    njiffy=$temp[(ws:|:)1]
    mode=$temp[(ws:|:)2]
    thres=$temp[(ws:|:)3]
    time=$(date +%s)
    difference=$(( $time - $njiffy ))
fi


if [[ $mode == temper ||  ($difference -lt 2 &&  $1 == $p_subject ) ]];then
    if [[ $thres == 0 ]];then
        if [[ ! $mode == "temper" ]];then
            notify-send -f "Warning" "Too many notifications - check:/tmp/notifications"
            mode="temper"
        fi

        echo  "$time|$mode|$maxthres" >| $NFILE
        echo  "$1" >> $NFILE
        echo "$(date -R): $@" >>| /tmp/notifications
        exit
    else
        thres=$(( (thres-1)%$maxthres ))
    fi
    
elif [[ $difference -lt 10 ]];then
    mode="batch"
    thres=10
    duration=2
else
    mode="shot"
    duration=7
    thres=10
fi
echo  "$time|$mode|$thres" >| $NFILE
echo  "$1" >> $NFILE
#set +x

prgm=$0

if [[ -n $1 ]];then
    param="${(qq)1}"
    shift
    mlog="${(qq)@}"
    if [[ ! -t 0 ]];then
        while read LINE
        do
            mlog="$mlog ${(qq)LINE}"
        done
    fi
else
    if [[  -t 0 ]];then
        notify-send "Warning" "Wrong input"
        exit
    fi
    param="Subject"
    tempReply=""
    while read LINE
    do
        tempReply="$tempReply ${(qq)LINE}"
    done
    echo -e "STDIN \n$(date '+%F %H:%M') ==> $param: $tempReply\n" >>| ~/.notify-history
    $type "$param" "$tempReply"
    exit
fi

if [[ $prgm == *aria* ]];then
    param="aria2c"
fi

if [[ $prgm == *beuter* ]];then
    mlog="^i(/home/raghavendra/.notify-icons/beuter.xpm)$param $mlog"
    param="beuter"
fi

echo -e "\n$(date '+%F %H:%M') ==> $mlog\n" >> ~/.notify-history

case $param in
    *rtorrent*)
        $type "Torrent download" "^i(/home/raghavendra/.notify-icons/torrent.xpm)$mlog download complete!"
      consume $HOME/.dque
      ;;
      *aria2c*)
        message=$(tail -1 ~/.download_history |cut -d ' ' -f 1 | cut -d : -f 2-)
        $type "Aria2:" "^i(/home/raghavendra/.notify-icons/download.xpm)${message:t}  download complete"
        consume $HOME/.dque
        ;;
    *beuter*)
       $type "Newsbeuter" "$mlog"
        ;;
     *mail*)
        $type "New Mail" "$mlog"
         ;;
     *) $type "$param" "$mlog"
esac
