#!/bin/zsh
#sleep 60
export DISPLAY=":0"
tasks="$(print -n ~/.tasks/*.remain 2>/dev/null | wc -l)"
#cookie="$(fortune -n 200 -a -s matrix calvin house computers paradoxum issa-haiku humorists archlinux linuxcookie debian goedel literature tbbt perl startrek the-godfather science linux  wisdom | tr -d '<' | tr '>' ':')"
cookie="$(fortune -n 200 -a -s | tr -d '<' | tr '>' ':')"

#~/bin/notify-send "Reminder" "Tasks left: <b>$tasks</b>

#<i>$(date -R)</i>
#----------------------
#$cookie"
~/bin/notify-send "Reminder" "^i(/home/raghavendra/.notify-icons/reminder.xpm)Tasks left:$tasks | $(date -R) | $cookie"
exit 0
#sleep 2
#mtasks="
#"
#counter=1

#if [[ $tasks > 0 ]];then
    #for t in ~/.tasks/*.remain;do
        #mtasks="$mtasks
        #Task#$counter: ${t:r:t}
        #$(cat $t)
        #"
        #counter=$(($counter+1))
        #if [[ $counter > 4 ]];then break;fi
    #done
#fi
#~/bin/notify-send "$mtasks"

