#!/bin/zsh
#sleep 60
export DISPLAY=":0"
tasks="$(/bin/ls -A ~/.tasks/*.remain 2>/dev/null | wc -l)"
cookie="$(fortune -n 200 -a -s matrix calvin house computers paradoxum issa-haiku humorists archlinux lorquotes debian goedel literature tbbt perl startrek the-godfather science linux linuxcookie wisdom | tr -d '<' | tr '>' ':')"
~/bin/notify-send "Reminder" "Tasks left: <b>$tasks</b>

<i>$(date -R)</i>
----------------------
$cookie"
exit 0
#sleep 2
#mtasks="
#"
#counter=1

#if [[ $tasks > 0 ]];then
    #for t in ~/.tasks/*.remain;do
        #mtasks="$mtasks
        #Task#$counter: ${t:r:t}
        #$(cat $t)
        #"
        #counter=$(($counter+1))
        #if [[ $counter > 4 ]];then break;fi
    #done
#fi
#~/bin/notify-send "$mtasks"

