#!/bin/zsh
# tmux-open-url - open last URL in current tmux pane in firefox

#LAST_URL=$(tmux capture-pane -b1 \; show-buffer -b1 \; delete-buffer -b1 |
#           grep -P -o '(?:https?://|ftp://|news://|mailto:|file://|\bwww\.)[a-zA-Z0-9\-\@;\/?:&=%\$_.+!*\x27,~#]*(\([a-zA-Z0-9\-\@;\/?:&=%\$_.+!*\x27,~#]*\)|[a-zA-Z0-9\-\@;\/?:&=%\$_+*~])+' | tac | $DMENU)


tmux capture-pane
tmux save-buffer /tmp/mux-buffer
LAST_URL=$(/bin/grep  -i -o -P '(https?://|www.)[0-9A-Z\.\/\-\_~\?]*' 2>/dev/null /tmp/mux-buffer | tac | $DMENU)
[ -n "$LAST_URL" ] && $BROWSER "$LAST_URL"
