#!/bin/zsh

tmux capture-pane
tmux save-buffer /tmp/mux-buffer
LAST_URL=$(/bin/grep  -i -o -P '(https?://|www.)[0-9A-Z\.\/\-\_~\?=]*' 2>/dev/null /tmp/mux-buffer | tac | $=DMENU)
[ -n "$LAST_URL" ] && browser "$=LAST_URL"
