#!/bin/sh

if  [[ $1 = '1' ]];then curvol="+5" ;fi
if  [[ $1 = '2' ]];then ossmix jack.fp-green.fp-headphone -- -10;exit;fi
if  [[ $1 = '3' ]];then if [ $curvol = "0.0" ];then curvol=55.0;else curvol=0;fi;fi

ossmix jack.fp-green.fp-headphone "$curvol"
