#!/bin/zsh

max="69.4"
#set -x
if [[ $1 = 'cur' ]];then 
    cur=$(ossmix jack.fp-green.fp-headphone | awk '{ print $10 }'); 
    cur=$(( ${cur#*:}/64.4 * 100.0 ))
    printf "♪ %.2f ♪" $cur
    exit
fi

#set +x
if  [[ $1 = '1' ]];then curvol="+5" ;fi
if  [[ $1 = '2' ]];then ossmix jack.fp-green.fp-headphone -- -10;exit;fi
if  [[ $1 = '3' ]];then if [[ $curvol = "0.0" ]];then curvol=55.0;else curvol=0;fi;fi

ossmix jack.fp-green.fp-headphone "$curvol"
