#!/bin/zsh
#set -x

isurl () {
        url="$@" 
        curl -I -s "$url" &> /dev/null || return 1
        return 0
}

session="uake"
own=$$

if [[ -z $TMUX || $1 == -f ]];then
    [[ $1 == -f ]] && shift
    /usr/bin/w3m "$@"
fi

if ! ps auxww | =grep -i w3m | =grep -v $own |  =grep -vq grep;then 
    lastone=$(( $(tmux list-windows -t $session | wc -l) + 2 )) 
    tmux new-window -d -t $session:$lastone "/usr/bin/w3m lwn.net"
    tmux join-pane -s $session:$lastone -p 80
    exit
else
    winum=$(~/bin/tux tnum w3m)
fi

if [[ $? != 0 ]];then 
	print "Failed"
        return
fi
#set +x



keys=""

for f in $@;do
    if isurl $f;then 
        :
    else
         if [[ $f == /* ]];then
             prefix=
         else
             prefix="$PWD/"
         fi
         f="${prefix}$f"
         if [[ ! -f $f ]];then
            echo "Failed"
            exit 1
         fi
    fi
    tmux send-keys -t $session:$winum 'C-c' 'T' "$f" 'Enter'
done

if [[ -t 1 ]];then
    tmux join-pane -s $session:$winum -p 75 
else
    tmux select-window -t $session:$winum  
fi
#set +x
